const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const test_step = b.step("test", "Run unit tests");

    const zmath_dep = b.dependency("zmath", .{});

    { // simulation executable
        const exe_mod = b.createModule(.{
            .root_source_file = b.path("src/flip7_sim.zig"),
            .target = target,
            .optimize = optimize,
        });
        const exe = b.addExecutable(.{
            .name = "flip7_sim",
            .root_module = exe_mod,
        });
        b.installArtifact(exe);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(b.getInstallStep());
        if (b.args) |args| run_cmd.addArgs(args);
        const run_step = b.step("run-sim", "Run the simulation");
        run_step.dependOn(&run_cmd.step);

        const run_tests = b.addRunArtifact(b.addTest(.{ .root_module = exe_mod }));
        test_step.dependOn(&run_tests.step);
    }

    const freetype_dep = b.dependency("freetype", .{});
    const freetype = buildFreetype(b, target, optimize, freetype_dep, false);
    b.installArtifact(freetype);

    { // game executable
        const sdl_dep = b.dependency("sdl", .{
            .target = target,
            .optimize = optimize,
        });
        const sdl_lib = sdl_dep.artifact("SDL3");

        // --- zlib ------------------------------------------------------------
        const zlib_dep = b.dependency("zlib", .{});
        const zlib_mod = b.createModule(.{ .target = target, .optimize = optimize });
        zlib_mod.addIncludePath(zlib_dep.path("."));
        zlib_mod.addCSourceFiles(.{
            .root = zlib_dep.path("."),
            .files = &.{
                "adler32.c", "compress.c", "crc32.c",   "deflate.c",
                "infback.c", "inffast.c",  "inflate.c", "inftrees.c",
                "trees.c",   "uncompr.c",  "zutil.c",
            },
            .flags = &.{"-std=c89"},
        });
        zlib_mod.link_libc = true;
        const zlib = b.addLibrary(.{ .name = "z", .root_module = zlib_mod });

        // --- libpng ----------------------------------------------------------
        const libpng_dep = b.dependency("libpng", .{});

        // pnglibconf.h is normally generated by configure; use the prebuilt
        // version that ships in scripts/ (sets PNG_ZLIB_VERNUM 0, skipping the
        // version-mismatch check that would otherwise fire).
        const libpng_config = b.addWriteFiles();
        const pnglibconf_h = libpng_config.addCopyFile(
            libpng_dep.path("scripts/pnglibconf.h.prebuilt"),
            "pnglibconf.h",
        );

        const libpng_mod = b.createModule(.{ .target = target, .optimize = optimize });
        libpng_mod.addIncludePath(libpng_dep.path("."));
        libpng_mod.addIncludePath(zlib_dep.path("."));
        libpng_mod.addIncludePath(pnglibconf_h.dirname());
        libpng_mod.addCSourceFiles(.{
            .root = libpng_dep.path("."),
            .files = &.{
                "png.c",      "pngerror.c", "pngget.c",   "pngmem.c",
                "pngpread.c", "pngread.c",  "pngrio.c",   "pngrtran.c",
                "pngrutil.c", "pngset.c",   "pngtrans.c", "pngwio.c",
                "pngwrite.c", "pngwtran.c", "pngwutil.c",
            },
            .flags = &.{"-std=c89"},
        });
        libpng_mod.link_libc = true;
        libpng_mod.linkLibrary(zlib);
        const libpng = b.addLibrary(.{
            .name = "png",
            .root_module = libpng_mod,
            .linkage = .static,
        });

        // --- exe module ------------------------------------------------------
        const exe_mod = b.createModule(.{
            .root_source_file = b.path("src/main_native.zig"),
            .target = target,
            .optimize = optimize,
        });
        exe_mod.linkLibrary(sdl_lib);
        exe_mod.linkLibrary(libpng);
        exe_mod.linkLibrary(freetype);
        exe_mod.addIncludePath(libpng_dep.path("."));
        exe_mod.addIncludePath(zlib_dep.path("."));
        exe_mod.addIncludePath(pnglibconf_h.dirname());
        exe_mod.addIncludePath(freetype_dep.path("include"));
        exe_mod.addImport("zmath", zmath_dep.module("root"));

        const exe = b.addExecutable(.{
            .name = "flip7",
            .root_module = exe_mod,
        });
        b.installArtifact(exe);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(b.getInstallStep());
        if (b.args) |args| run_cmd.addArgs(args);
        const run_step = b.step("run", "Run the app");
        run_step.dependOn(&run_cmd.step);

        const exe_tests = b.addTest(.{ .root_module = exe_mod });
        const run_tests = b.addRunArtifact(exe_tests);
        test_step.dependOn(&run_tests.step);
    }

    const build_wasm = b.option(bool, "wasm", "Build the WebAssembly module (default: true)") orelse true;
    if (build_wasm) { // wasm module
        const wasm_target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
            .cpu_features_add = std.Target.wasm.featureSet(&.{.exception_handling}),
        });

        const wasm_mod = b.createModule(.{
            .root_source_file = b.path("src/main_wasm.zig"),
            .target = wasm_target,
            .optimize = optimize,
        });
        wasm_mod.addImport("zmath", zmath_dep.module("root"));
        const freetype_wasm = buildFreetype(b, wasm_target, optimize, freetype_dep, true);
        wasm_mod.linkLibrary(freetype_wasm);
        wasm_mod.addIncludePath(freetype_dep.path("include"));
        wasm_mod.addIncludePath(b.path("src"));
        wasm_mod.addCMacro("FT_CONFIG_STANDARD_LIBRARY_H", "\"freetype_wasm_stdlib.h\"");

        const wasm_exe = b.addExecutable(.{
            .name = "flip7",
            .root_module = wasm_mod,
        });
        wasm_exe.entry = .disabled;
        wasm_exe.rdynamic = true;
        const install_wasm = b.addInstallArtifact(wasm_exe, .{});
        const wasm_step = b.step("wasm", "Build WebGL module (wasm32-wasi)");
        wasm_step.dependOn(&install_wasm.step);

        const install_html = b.addInstallBinFile(b.path("static/index.html"), "index.html");
        wasm_step.dependOn(&install_html.step);

        const install_js = b.addInstallBinFile(b.path("static/webgl.js"), "webgl.js");
        wasm_step.dependOn(&install_js.step);

        const install_textures = b.addInstallDirectory(.{
            .source_dir = b.path("src/cards"),
            .install_dir = .bin,
            .install_subdir = "cards",
            .include_extensions = &[_][]const u8{".png"},
        });
        wasm_step.dependOn(&install_textures.step);

        b.getInstallStep().dependOn(wasm_step);
    }
}

fn buildFreetype(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode, lib_dep: *std.Build.Dependency, wasm_no_libc: bool) *std.Build.Step.Compile {
    const lib_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
    });

    const flags: []const []const u8 = if (wasm_no_libc) &.{
        "-DFT2_BUILD_LIBRARY",
        "-DFT_CONFIG_OPTION_SYSTEM_ZLIB=0",
        "-DFT_CONFIG_OPTION_DISABLE_STREAM_SUPPORT",
        "-DFT_CONFIG_STANDARD_LIBRARY_H=\"freetype_wasm_stdlib.h\"",
        "-fwasm-exceptions",
        "-fno-sanitize=undefined",
    } else &.{
        "-DFT2_BUILD_LIBRARY",
        "-DFT_CONFIG_OPTION_SYSTEM_ZLIB=1",
        "-DHAVE_UNISTD_H",
        "-DHAVE_FCNTL_H",
        "-fno-sanitize=undefined",
    };
    const common_sources: []const []const u8 = &.{
        "autofit/autofit.c",
        "base/ftbase.c",
        "base/ftbbox.c",
        "base/ftbdf.c",
        "base/ftbitmap.c",
        "base/ftcid.c",
        "base/ftfstype.c",
        "base/ftgasp.c",
        "base/ftglyph.c",
        "base/ftgxval.c",
        "base/ftinit.c",
        "base/ftmm.c",
        "base/ftotval.c",
        "base/ftpatent.c",
        "base/ftpfr.c",
        "base/ftstroke.c",
        "base/ftsynth.c",
        "base/fttype1.c",
        "base/ftwinfnt.c",
        "bdf/bdf.c",
        "cache/ftcache.c",
        "cff/cff.c",
        "cid/type1cid.c",
        "pcf/pcf.c",
        "pfr/pfr.c",
        "psaux/psaux.c",
        "pshinter/pshinter.c",
        "psnames/psnames.c",
        "raster/raster.c",
        "sdf/sdf.c",
        "sfnt/sfnt.c",
        "smooth/smooth.c",
        "svg/svg.c",
        "truetype/truetype.c",
        "type1/type1.c",
        "type42/type42.c",
        "winfonts/winfnt.c",
        "hvf/hvf.c",
    };
    // compressed font sources require zlib/bzip2 — skip on wasm
    const compressed_sources: []const []const u8 = &.{
        "bzip2/ftbzip2.c",
        "gzip/ftgzip.c",
        "lzw/ftlzw.c",
    };
    lib_mod.addCSourceFiles(.{ .root = lib_dep.path("src"), .files = common_sources, .flags = flags });
    if (!wasm_no_libc) {
        lib_mod.addCSourceFiles(.{ .root = lib_dep.path("src"), .files = compressed_sources, .flags = flags });
    }
    lib_mod.addIncludePath(lib_dep.path("include"));
    if (wasm_no_libc) {
        lib_mod.addIncludePath(b.path("src"));
    } else {
        lib_mod.link_libc = true;
    }

    if (wasm_no_libc) {
        lib_mod.addCSourceFile(.{
            .file = b.path("src/freetype_wasm_stubs.c"),
            .flags = flags,
        });
        // wasm SjLj runtime (needed for setjmp/longjmp via -fwasm-exceptions)
        lib_mod.addCSourceFile(.{
            .file = .{ .cwd_relative = "/usr/lib/zig/libc/wasi/libc-top-half/musl/src/setjmp/wasm32/rt.c" },
            .flags = &.{ "-fwasm-exceptions", "-mcpu=generic+exception-handling" },
        });
    } else switch (target.result.os.tag) {
        .linux => lib_mod.addCSourceFile(.{
            .file = lib_dep.path("builds/unix/ftsystem.c"),
            .flags = flags,
        }),
        .windows => lib_mod.addCSourceFile(.{
            .file = lib_dep.path("builds/windows/ftsystem.c"),
            .flags = flags,
        }),
        else => lib_mod.addCSourceFile(.{
            .file = lib_dep.path("src/base/ftsystem.c"),
            .flags = flags,
        }),
    }
    if (!wasm_no_libc) switch (target.result.os.tag) {
        .windows => {
            lib_mod.addCSourceFile(.{
                .file = lib_dep.path("builds/windows/ftdebug.c"),
                .flags = flags,
            });
            lib_mod.addWin32ResourceFile(.{
                .file = lib_dep.path("src/base/ftver.rc"),
            });
        },
        else => lib_mod.addCSourceFile(.{
            .file = lib_dep.path("src/base/ftdebug.c"),
            .flags = flags,
        }),
    };

    return b.addLibrary(.{
        .name = if (wasm_no_libc) "freetype-wasm" else "freetype",
        .linkage = .static,
        .root_module = lib_mod,
    });
}
