const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const test_step = b.step("test", "Run unit tests");

    { // simulation executable
        const exe_mod = b.createModule(.{
            .root_source_file = b.path("src/flip7_sim.zig"),
            .target = target,
            .optimize = optimize,
        });
        const exe = b.addExecutable(.{
            .name = "flip7_sim",
            .root_module = exe_mod,
        });
        b.installArtifact(exe);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(b.getInstallStep());
        if (b.args) |args| run_cmd.addArgs(args);
        const run_step = b.step("run-sim", "Run the simulation");
        run_step.dependOn(&run_cmd.step);

        const run_tests = b.addRunArtifact(b.addTest(.{ .root_module = exe_mod }));
        test_step.dependOn(&run_tests.step);
    }

    { // game executable
        const sdl_dep = b.dependency("sdl", .{
            .target = target,
            .optimize = optimize,
        });
        const sdl_lib = sdl_dep.artifact("SDL3");

        // --- zlib ------------------------------------------------------------
        const zlib_dep = b.dependency("zlib", .{});
        const zlib_mod = b.createModule(.{ .target = target, .optimize = optimize });
        zlib_mod.addIncludePath(zlib_dep.path("."));
        zlib_mod.addCSourceFiles(.{
            .root = zlib_dep.path("."),
            .files = &.{
                "adler32.c", "compress.c", "crc32.c",   "deflate.c",
                "infback.c", "inffast.c",  "inflate.c", "inftrees.c",
                "trees.c",   "uncompr.c",  "zutil.c",
            },
            .flags = &.{"-std=c89"},
        });
        zlib_mod.link_libc = true;
        const zlib = b.addLibrary(.{ .name = "z", .root_module = zlib_mod });

        // --- libpng ----------------------------------------------------------
        const libpng_dep = b.dependency("libpng", .{});

        // pnglibconf.h is normally generated by configure; use the prebuilt
        // version that ships in scripts/ (sets PNG_ZLIB_VERNUM 0, skipping the
        // version-mismatch check that would otherwise fire).
        const libpng_config = b.addWriteFiles();
        const pnglibconf_h = libpng_config.addCopyFile(
            libpng_dep.path("scripts/pnglibconf.h.prebuilt"),
            "pnglibconf.h",
        );

        const libpng_mod = b.createModule(.{ .target = target, .optimize = optimize });
        libpng_mod.addIncludePath(libpng_dep.path("."));
        libpng_mod.addIncludePath(zlib_dep.path("."));
        libpng_mod.addIncludePath(pnglibconf_h.dirname());
        libpng_mod.addCSourceFiles(.{
            .root = libpng_dep.path("."),
            .files = &.{
                "png.c",      "pngerror.c", "pngget.c",   "pngmem.c",
                "pngpread.c", "pngread.c",  "pngrio.c",   "pngrtran.c",
                "pngrutil.c", "pngset.c",   "pngtrans.c", "pngwio.c",
                "pngwrite.c", "pngwtran.c", "pngwutil.c",
            },
            .flags = &.{"-std=c89"},
        });
        libpng_mod.link_libc = true;
        libpng_mod.linkLibrary(zlib);
        const libpng = b.addLibrary(.{ .name = "png", .root_module = libpng_mod });

        // --- exe module ------------------------------------------------------
        const exe_mod = b.createModule(.{
            .root_source_file = b.path("src/main_native.zig"),
            .target = target,
            .optimize = optimize,
        });
        exe_mod.linkLibrary(sdl_lib);
        exe_mod.linkLibrary(libpng);
        exe_mod.addIncludePath(libpng_dep.path("."));
        exe_mod.addIncludePath(zlib_dep.path("."));
        exe_mod.addIncludePath(pnglibconf_h.dirname());

        const exe = b.addExecutable(.{
            .name = "flip7",
            .root_module = exe_mod,
        });
        b.installArtifact(exe);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(b.getInstallStep());
        if (b.args) |args| run_cmd.addArgs(args);
        const run_step = b.step("run", "Run the app");
        run_step.dependOn(&run_cmd.step);

        const exe_tests = b.addTest(.{ .root_module = exe_mod });
        const run_tests = b.addRunArtifact(exe_tests);
        test_step.dependOn(&run_tests.step);
    }

    { // wasm module
        const wasm_target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        });

        const wasm_mod = b.createModule(.{
            .root_source_file = b.path("src/main_wasm.zig"),
            .target = wasm_target,
            .optimize = optimize,
        });
        const wasm_exe = b.addExecutable(.{
            .name = "flip7",
            .root_module = wasm_mod,
        });
        wasm_exe.entry = .disabled;
        wasm_exe.rdynamic = true;
        const install_wasm = b.addInstallArtifact(wasm_exe, .{});
        const wasm_step = b.step("wasm", "Build WebGL module (wasm32-wasi)");
        wasm_step.dependOn(&install_wasm.step);

        const install_html = b.addInstallBinFile(b.path("static/index.html"), "index.html");
        wasm_step.dependOn(&install_html.step);

        const install_js = b.addInstallBinFile(b.path("static/webgl.js"), "webgl.js");
        wasm_step.dependOn(&install_js.step);

        const install_textures = b.addInstallDirectory(.{
            .source_dir = b.path("src/cards"),
            .install_dir = .bin,
            .install_subdir = "cards",
            .include_extensions = &[_][]const u8{".png"},
        });
        wasm_step.dependOn(&install_textures.step);

        b.getInstallStep().dependOn(wasm_step);
    }
}
